export const dummyState = {
  auth: {
    isLoaded: true,
    authenticated: true,
    error: null,
    user: {
      displayName: "Peach Chicken",
      email: "peach.chicken.993@test.com",
      isAnonymous: false,
      photoURL: null,
      uid: "uA7mzS2etz5oEIrivBa3iDoZHgZn",
    },
  },
  profile: {
    isLoaded: true,
    profile: {
      displayName: "Peach Chicken",
      genrePreference: [
        28,
        12,
        16,
        35,
        80,
        99,
        18,
        10751,
        14,
        36,
        27,
        10402,
        9648,
        10749,
        878,
        10770,
        53,
        10752,
        37,
      ],
      photoURL: null,
      uid: "uA7mzS2etz5oEIrivBa3iDoZHgZn",
      isAnonymous: false,
      email: "peach.chicken.993@test.com",
    },
    error: null,
  },
  windowSizing: {
    height: 823,
    width: 411,
    XCenter: 205.5,
  },
  voted: {
    isLoaded: false,
    Liked: [
      {
        original_language: "en",
        timeVoted: 1608182331586,
        isLike: true,
        imdb_id: "tt0805647",
        displayName: "Peach Chicken",
        genrePreference: [
          28,
          12,
          16,
          35,
          80,
          99,
          18,
          10751,
          14,
          36,
          27,
          10402,
          9648,
          10749,
          878,
          10770,
          53,
          10752,
          37,
        ],
        video: false,
        title: "Roald Dahl's The Witches",
        backdrop_path: "/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg",
        photoURL: null,
        uid: "uA7mzS2etz5oEIrivBa3iDoZHgZn",
        revenue: 0,
        genres: [
          {
            name: "Fantasy",
            id: 14,
          },
          {
            name: "Family",
            id: 10751,
          },
          {
            name: "Adventure",
            id: 12,
          },
          {
            name: "Comedy",
            id: 35,
          },
          {
            name: "Horror",
            id: 27,
          },
        ],
        popularity: 1868.653,
        release_dates: {
          results: [
            {
              iso_3166_1: "DE",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: "de",
                  certification: "12",
                  release_date: "2020-10-29T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "FI",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-12-11T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "UA",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-10-29T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "US",
              release_dates: [
                {
                  note: "HBO Max",
                  type: 4,
                  iso_639_1: "",
                  certification: "PG",
                  release_date: "2020-10-22T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "PT",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "M/12",
                  release_date: "2020-10-29T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "GB",
              release_dates: [
                {
                  note: "",
                  type: 4,
                  iso_639_1: null,
                  certification: "PG",
                  release_date: "2020-10-26T00:00:00.000Z",
                },
                {
                  note: "DVD",
                  type: 5,
                  iso_639_1: null,
                  certification: "PG",
                  release_date: "2020-12-14T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "HU",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "12",
                  release_date: "2020-11-05T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "NL",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "9",
                  release_date: "2020-11-18T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "FR",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-12-23T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "AU",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: "",
                  certification: "M",
                  release_date: "2020-12-10T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "IE",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "PG",
                  release_date: "2020-10-26T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "HK",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-10-29T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "TW",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "普遍級",
                  release_date: "2020-11-05T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "CZ",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-11-19T00:00:00.000Z",
                },
              ],
            },
          ],
        },
        production_countries: [
          {
            iso_3166_1: "MX",
            name: "Mexico",
          },
          {
            iso_3166_1: "US",
            name: "United States of America",
          },
        ],
        id: 531219,
        vote_count: 931,
        email: "peach.chicken.993@test.com",
        budget: 0,
        overview:
          "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
        original_title: "Roald Dahl's The Witches",
        runtime: 106,
        genre_ids: [14, 10751, 12, 35, 27],
        poster_path: "/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
        spoken_languages: [
          {
            iso_639_1: "en",
            english_name: "English",
            name: "English",
          },
          {
            iso_639_1: "nl",
            english_name: "Dutch",
            name: "Nederlands",
          },
        ],
        isAnonymous: false,
        release_date: "2020-10-26",
        production_companies: [
          {
            logo_path: "/5vSBzUwnCcaF90ZTchG3LwRKQ2M.png",
            origin_country: "US",
            name: "ImageMovers",
            id: 11395,
          },
          {
            logo_path: "/ky0xOc5OrhzkZ1N6KyUxacfQsCk.png",
            origin_country: "US",
            name: "Warner Bros. Pictures",
            id: 174,
          },
          {
            logo_path: null,
            origin_country: "US",
            name: "Double Dare You Productions",
            id: 101082,
          },
          {
            logo_path: null,
            origin_country: "MX",
            name: "Esperanto Filmoj",
            id: 141325,
          },
          {
            logo_path: "/dHfP8fUyykmTsMXbtXO0kSsYz5E.png",
            origin_country: "US",
            name: "The Jim Henson Company",
            id: 6254,
          },
          {
            logo_path: null,
            origin_country: "US",
            name: "Necropia Entertainment",
            id: 11627,
          },
        ],
        vote_average: 6.9,
        belongs_to_collection: null,
        tagline: "They're real!",
        adult: false,
        homepage: "https://www.thewitchesmovie.net/",
        status: "Released",
        timeMatched: 1608185774064,
        matchedWith: [
          {
            displayName: "Otter Algae",
            email: "otter.algae.908@test.com",
            isAnonymous: false,
            photoURL: null,
            uid: "wFKYBpIoL7rKuMl90M9vFJ3Huh30",
            genrePreference: [
              28,
              12,
              16,
              35,
              80,
              99,
              18,
              10751,
              14,
              36,
              27,
              10402,
              9648,
              10749,
              878,
              10770,
              53,
              10752,
              37,
            ],
          },
        ],
        notify: false,
      },
      {
        original_language: "en",
        timeVoted: 1608186108017,
        isLike: true,
        imdb_id: "tt9624766",
        displayName: "Peach Chicken",
        genrePreference: [
          28,
          12,
          16,
          35,
          80,
          99,
          18,
          10751,
          14,
          36,
          27,
          10402,
          9648,
          10749,
          878,
          10770,
          53,
          10752,
          37,
        ],
        video: false,
        title: "Jiu Jitsu",
        backdrop_path: "/jeAQdDX9nguP6YOX6QSWKDPkbBo.jpg",
        photoURL: null,
        uid: "uA7mzS2etz5oEIrivBa3iDoZHgZn",
        revenue: 74000000,
        genres: [
          {
            name: "Action",
            id: 28,
          },
          {
            name: "Fantasy",
            id: 14,
          },
          {
            name: "Science Fiction",
            id: 878,
          },
        ],
        popularity: 1802.147,
        release_dates: {
          results: [
            {
              iso_3166_1: "US",
              release_dates: [
                {
                  note: "",
                  type: 2,
                  iso_639_1: "",
                  certification: "R",
                  release_date: "2020-11-20T00:00:00.000Z",
                },
                {
                  note: "",
                  type: 4,
                  iso_639_1: null,
                  certification: "R",
                  release_date: "2020-11-20T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "RU",
              release_dates: [
                {
                  note: "",
                  type: 4,
                  iso_639_1: null,
                  certification: "18+",
                  release_date: "2020-11-24T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "FI",
              release_dates: [
                {
                  note: "Night Visions Film Festival",
                  type: 1,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2021-01-15T00:00:00.000Z",
                },
              ],
            },
          ],
        },
        production_countries: [
          {
            iso_3166_1: "CY",
            name: "Cyprus",
          },
          {
            iso_3166_1: "US",
            name: "United States of America",
          },
        ],
        id: 590706,
        vote_count: 161,
        email: "peach.chicken.993@test.com",
        budget: 23000000,
        overview:
          "Every six years, an ancient order of jiu-jitsu fighters joins forces to battle a vicious race of alien invaders. But when a celebrated war hero goes down in defeat, the fate of the planet and mankind hangs in the balance.",
        original_title: "Jiu Jitsu",
        runtime: 102,
        genre_ids: [28, 14, 878],
        poster_path: "/eLT8Cu357VOwBVTitkmlDEg32Fs.jpg",
        spoken_languages: [
          {
            iso_639_1: "en",
            english_name: "English",
            name: "English",
          },
        ],
        isAnonymous: false,
        release_date: "2020-11-20",
        production_companies: [
          {
            logo_path: null,
            origin_country: "US",
            name: "Acme Rocket Fuel",
            id: 141998,
          },
          {
            logo_path: null,
            origin_country: "CY",
            name: "Green Olive Films",
            id: 138013,
          },
        ],
        vote_average: 5.7,
        belongs_to_collection: null,
        tagline: "From the darkness, the ultimate fighter rises.",
        adult: false,
        homepage: "https://www.paramountmovies.com/movies/jiu-jitsu",
        status: "Released",
        timeMatched: 1608186109762,
        matchedWith: [
          {
            displayName: "Otter Algae",
            email: "otter.algae.908@test.com",
            isAnonymous: false,
            photoURL: null,
            uid: "wFKYBpIoL7rKuMl90M9vFJ3Huh30",
            genrePreference: [
              28,
              12,
              16,
              35,
              80,
              99,
              18,
              10751,
              14,
              36,
              27,
              10402,
              9648,
              10749,
              878,
              10770,
              53,
              10752,
              37,
            ],
          },
        ],
        notify: false,
      },
      {
        original_language: "en",
        timeVoted: 1608185316206,
        isLike: true,
        imdb_id: "tt9689696",
        displayName: "Peach Chicken",
        genrePreference: [
          28,
          12,
          16,
          35,
          80,
          99,
          18,
          10751,
          14,
          36,
          27,
          10402,
          9648,
          10749,
          878,
          10770,
          53,
          10752,
          37,
        ],
        video: false,
        title: "Wander",
        backdrop_path: "/wk58aoyWpMTVkKkdjw889XfWGdL.jpg",
        photoURL: null,
        uid: "uA7mzS2etz5oEIrivBa3iDoZHgZn",
        revenue: 0,
        genres: [
          {
            name: "Thriller",
            id: 53,
          },
          {
            name: "Crime",
            id: 80,
          },
          {
            name: "Mystery",
            id: 9648,
          },
        ],
        popularity: 1678.596,
        release_dates: {
          results: [
            {
              iso_3166_1: "US",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "R",
                  release_date: "2020-12-04T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "CA",
              release_dates: [
                {
                  note: "CIFF",
                  type: 1,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-09-29T00:00:00.000Z",
                },
                {
                  note: "",
                  type: 4,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-12-04T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "NL",
              release_dates: [
                {
                  note: "",
                  type: 4,
                  iso_639_1: "",
                  certification: "",
                  release_date: "2020-12-04T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "FR",
              release_dates: [
                {
                  note: "Deauville Film Festival",
                  type: 1,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-09-11T00:00:00.000Z",
                },
              ],
            },
          ],
        },
        production_countries: [
          {
            iso_3166_1: "CA",
            name: "Canada",
          },
          {
            iso_3166_1: "US",
            name: "United States of America",
          },
        ],
        id: 646593,
        vote_count: 27,
        email: "peach.chicken.993@test.com",
        budget: 0,
        overview:
          "After getting hired to probe a suspicious death in the small town of Wander, a mentally unstable private investigator becomes convinced the case is linked to the same 'conspiracy cover up' that caused the death of his daughter.",
        original_title: "Wander",
        runtime: 94,
        genre_ids: [53, 80, 9648],
        poster_path: "/2AwPvNHphpZBJDqjZKVuMAbvS0v.jpg",
        spoken_languages: [
          {
            iso_639_1: "en",
            english_name: "English",
            name: "English",
          },
        ],
        isAnonymous: false,
        release_date: "2020-12-04",
        production_companies: [
          {
            logo_path: null,
            origin_country: "",
            name: "WANGO Films",
            id: 40157,
          },
          {
            logo_path: "/6Vk4WZnKJuC6z6HKBGFirbWwWwV.png",
            origin_country: "US",
            name: "Aloe Entertainment",
            id: 5322,
          },
          {
            logo_path: null,
            origin_country: "US",
            name: "Don Kee Productions",
            id: 125092,
          },
          {
            logo_path: null,
            origin_country: "",
            name: "Falconer Pictures",
            id: 57413,
          },
          {
            logo_path: null,
            origin_country: "",
            name: "Verdi Productions",
            id: 37765,
          },
          {
            logo_path: null,
            origin_country: "",
            name: "Ironic Misnomer",
            id: 144301,
          },
        ],
        vote_average: 5.6,
        belongs_to_collection: null,
        tagline: "The conspiracy is real.",
        adult: false,
        homepage: "https://www.paramountmovies.com/movies/Wander",
        status: "Released",
        timeMatched: 1608185774216,
        matchedWith: [
          {
            displayName: "Otter Algae",
            email: "otter.algae.908@test.com",
            isAnonymous: false,
            photoURL: null,
            uid: "wFKYBpIoL7rKuMl90M9vFJ3Huh30",
            genrePreference: [
              28,
              12,
              16,
              35,
              80,
              99,
              18,
              10751,
              14,
              36,
              27,
              10402,
              9648,
              10749,
              878,
              10770,
              53,
              10752,
              37,
            ],
          },
        ],
        notify: false,
      },
    ],
    DisLiked: [],
    Watched: [
      {
        original_language: "en",
        timeVoted: 1608182283611,
        isLike: true,
        imdb_id: "tt4685762",
        displayName: "Peach Chicken",
        timeMatched: 1608182284271,
        genrePreference: [
          28,
          12,
          16,
          35,
          80,
          99,
          18,
          10751,
          14,
          36,
          27,
          10402,
          9648,
          10749,
          878,
          10770,
          53,
          10752,
          37,
        ],
        video: false,
        title: "The Craft: Legacy",
        notify: true,
        backdrop_path: "/lIE7kfdLBRd0KENNtOaIqPPWNqh.jpg",
        photoURL: null,
        uid: "uA7mzS2etz5oEIrivBa3iDoZHgZn",
        watchedWith: [
          {
            displayName: "Otter Algae",
            genrePreference: [
              28,
              12,
              16,
              35,
              80,
              99,
              18,
              10751,
              14,
              36,
              27,
              10402,
              9648,
              10749,
              878,
              10770,
              53,
              10752,
              37,
            ],
            photoURL: null,
            uid: "wFKYBpIoL7rKuMl90M9vFJ3Huh30",
            isAnonymous: false,
            email: "otter.algae.908@test.com",
          },
        ],
        revenue: 0,
        genres: [
          {
            name: "Horror",
            id: 27,
          },
          {
            name: "Drama",
            id: 18,
          },
          {
            name: "Fantasy",
            id: 14,
          },
        ],
        popularity: 1475.549,
        release_dates: {
          results: [
            {
              iso_3166_1: "FR",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-10-28T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "GB",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: "",
                  certification: "15",
                  release_date: "2020-10-28T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "UA",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-10-29T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "RU",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "18+",
                  release_date: "2020-11-19T00:00:00.000Z",
                },
                {
                  note: "",
                  type: 4,
                  iso_639_1: null,
                  certification: "18+",
                  release_date: "2020-12-24T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "US",
              release_dates: [
                {
                  note: "",
                  type: 4,
                  iso_639_1: "",
                  certification: "PG-13",
                  release_date: "2020-10-28T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "TW",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "保護級",
                  release_date: "2020-10-30T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "CA",
              release_dates: [
                {
                  note: "",
                  type: 4,
                  iso_639_1: null,
                  certification: "",
                  release_date: "2020-10-28T00:00:00.000Z",
                },
              ],
            },
            {
              iso_3166_1: "DE",
              release_dates: [
                {
                  note: "",
                  type: 3,
                  iso_639_1: null,
                  certification: "12",
                  release_date: "2020-10-29T00:00:00.000Z",
                },
              ],
            },
          ],
        },
        production_countries: [
          {
            iso_3166_1: "US",
            name: "United States of America",
          },
        ],
        id: 590995,
        matchedWith: [
          {
            displayName: "Otter Algae",
            genrePreference: [
              28,
              12,
              16,
              35,
              80,
              99,
              18,
              10751,
              14,
              36,
              27,
              10402,
              9648,
              10749,
              878,
              10770,
              53,
              10752,
              37,
            ],
            photoURL: null,
            uid: "wFKYBpIoL7rKuMl90M9vFJ3Huh30",
            isAnonymous: false,
            email: "otter.algae.908@test.com",
          },
        ],
        vote_count: 175,
        email: "peach.chicken.993@test.com",
        budget: 0,
        overview:
          "An eclectic foursome of aspiring teenage witches get more than they bargained for as they lean into their newfound powers.",
        original_title: "The Craft: Legacy",
        runtime: 94,
        genre_ids: [27, 18, 14],
        poster_path: "/lhMIra0pqWNuD6CIXoTmGwZ0EBS.jpg",
        timeWatched: 1608182288381,
        spoken_languages: [
          {
            iso_639_1: "en",
            english_name: "English",
            name: "English",
          },
        ],
        isAnonymous: false,
        release_date: "2020-10-28",
        production_companies: [
          {
            logo_path: "/kDedjRZwO8uyFhuHamomOhN6fzG.png",
            origin_country: "US",
            name: "Blumhouse Productions",
            id: 3172,
          },
          {
            logo_path: null,
            origin_country: "US",
            name: "Red Wagon Entertainment",
            id: 14440,
          },
          {
            logo_path: "/71BqEFAF4V3qjjMPCpLuyJFB9A.png",
            origin_country: "US",
            name: "Columbia Pictures",
            id: 5,
          },
        ],
        vote_average: 6.2,
        belongs_to_collection: {
          poster_path: "/6gblwKfs6KSPdB2xVXKbpA8CfQM.jpg",
          backdrop_path: "/rGF759srlDV2gdwBDpRLbN3Rv6m.jpg",
          name: "The Craft Collection",
          id: 758369,
        },
        tagline: "Let the ritual begin",
        adult: false,
        homepage:
          "https://www.sonypictures.com/movies/blumhousesthecraftlegacy",
        status: "Released",
      },
    ],
  },
  movieList: {
    movieList: [
      {
        adult: false,
        backdrop_path: "/kvexLqnJKZSMEu2CWNzNjlcMCNJ.jpg",
        genre_ids: [27, 37, 36],
        id: 294963,
        original_language: "en",
        original_title: "Bone Tomahawk",
        overview:
          "During a shootout in a saloon, Sheriff Hunt injures a suspicious stranger. One of the villagers takes care of him in prison. One day they both disappear – only the spear of a cannibal tribe is found. Hunt and a few of his men go in search of the prisoner and his nurse.",
        popularity: 828.775,
        poster_path: "/ifdPXLsGmdspNOonv3DwU5pbyVC.jpg",
        release_date: "2015-10-23",
        title: "Bone Tomahawk",
        video: false,
        vote_average: 6.8,
        vote_count: 1276,
        belongs_to_collection: null,
        budget: 1800000,
        genres: [
          {
            id: 27,
            name: "Horror",
          },
          {
            id: 37,
            name: "Western",
          },
          {
            id: 36,
            name: "History",
          },
        ],
        homepage: "",
        imdb_id: "tt2494362",
        production_companies: [
          {
            id: 11049,
            logo_path: null,
            name: "Caliber Media Company",
            origin_country: "",
          },
          {
            id: 78128,
            logo_path: null,
            name: "Realbuilder Productions",
            origin_country: "",
          },
          {
            id: 108781,
            logo_path: "/kHAIsNbR9DEiupDXYnloc9FyZl7.png",
            name: "Cinestate",
            origin_country: "US",
          },
          {
            id: 36109,
            logo_path: "/wca0Jcidf2N1KAPicYMjGoKOmYu.png",
            name: "The Fyzz",
            origin_country: "GB",
          },
        ],
        production_countries: [
          {
            iso_3166_1: "US",
            name: "United States of America",
          },
        ],
        revenue: 0,
        runtime: 132,
        spoken_languages: [
          {
            english_name: "English",
            iso_639_1: "en",
            name: "English",
          },
        ],
        status: "Released",
        tagline: "May the Lord have mercy and grant you a swift death",
        release_dates: {
          results: [
            {
              iso_3166_1: "PH",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-03-02T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "SE",
              release_dates: [
                {
                  certification: "15",
                  iso_639_1: null,
                  note: "",
                  release_date: "2016-09-05T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "AR",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: null,
                  note:
                    "Buenos Aires International Festival of Independent Cinema",
                  release_date: "2016-04-22T00:00:00.000Z",
                  type: 1,
                },
              ],
            },
            {
              iso_3166_1: "BE",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: null,
                  note: "Offscreen Film Festival",
                  release_date: "2016-03-18T00:00:00.000Z",
                  type: 1,
                },
              ],
            },
            {
              iso_3166_1: "CZ",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: null,
                  note: "",
                  release_date: "2016-09-28T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "ES",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: "es",
                  note: "Sitges International Film Festival",
                  release_date: "2015-10-11T00:00:00.000Z",
                  type: 1,
                },
                {
                  certification: "18",
                  iso_639_1: "es",
                  note: "",
                  release_date: "2016-03-18T00:00:00.000Z",
                  type: 3,
                },
                {
                  certification: "18",
                  iso_639_1: "es",
                  note: "",
                  release_date: "2016-04-20T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "RU",
              release_dates: [
                {
                  certification: "18+",
                  iso_639_1: "",
                  note: "",
                  release_date: "2015-12-10T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "PL",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-04-29T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "SG",
              release_dates: [
                {
                  certification: "R21",
                  iso_639_1: "",
                  note: "",
                  release_date: "2015-12-10T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "NO",
              release_dates: [
                {
                  certification: "18",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-11-04T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "RO",
              release_dates: [
                {
                  certification: "I.M.-18",
                  iso_639_1: null,
                  note: "",
                  release_date: "2016-07-08T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "IT",
              release_dates: [
                {
                  certification: "T",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-05-11T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "NL",
              release_dates: [
                {
                  certification: "16",
                  iso_639_1: "",
                  note: "International Film Festival Rotterdam",
                  release_date: "2016-01-29T00:00:00.000Z",
                  type: 1,
                },
              ],
            },
            {
              iso_3166_1: "IE",
              release_dates: [
                {
                  certification: "18",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-02-19T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "FR",
              release_dates: [
                {
                  certification: "16",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-05-11T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "PT",
              release_dates: [
                {
                  certification: "M/18",
                  iso_639_1: "",
                  release_date: "2017-01-26T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "GB",
              release_dates: [
                {
                  certification: "18",
                  iso_639_1: "en",
                  release_date: "2016-02-19T00:00:00.000Z",
                  type: 3,
                },
                {
                  certification: "18",
                  iso_639_1: "en",
                  note: "DVD",
                  release_date: "2016-06-13T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "GR",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: "",
                  release_date: "2016-06-23T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "UA",
              release_dates: [
                {
                  certification: "18",
                  iso_639_1: "uk",
                  note: "",
                  release_date: "2015-12-10T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "HU",
              release_dates: [
                {
                  certification: "18",
                  iso_639_1: null,
                  note: "",
                  release_date: "2016-07-07T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "US",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: "",
                  note: "Austin Fantastic Fest",
                  release_date: "2015-10-01T00:00:00.000Z",
                  type: 1,
                },
                {
                  certification: "NR",
                  iso_639_1: "",
                  note: "",
                  release_date: "2015-10-23T00:00:00.000Z",
                  type: 2,
                },
              ],
            },
            {
              iso_3166_1: "LV",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: null,
                  note: "",
                  release_date: "2015-12-18T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "BR",
              release_dates: [
                {
                  certification: "16",
                  iso_639_1: "pt",
                  release_date: "2016-08-29T00:00:00.000Z",
                  type: 4,
                },
                {
                  certification: "18",
                  iso_639_1: "",
                  note: "CALIFÓRNIA FILMES mj.gov.br",
                  release_date: "2016-09-28T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
            {
              iso_3166_1: "DE",
              release_dates: [
                {
                  certification: "18",
                  iso_639_1: "",
                  note: "",
                  release_date: "2016-01-21T00:00:00.000Z",
                  type: 3,
                },
              ],
            },
            {
              iso_3166_1: "JP",
              release_dates: [
                {
                  certification: "",
                  iso_639_1: null,
                  note: "",
                  release_date: "2016-12-02T00:00:00.000Z",
                  type: 5,
                },
              ],
            },
          ],
        },
      },
      {
        adult: false,
        backdrop_path: "/ckfwfLkl0CkafTasoRw5FILhZAS.jpg",
        genre_ids: [28, 35, 14],
        id: 602211,
        original_language: "en",
        original_title: "Fatman",
        overview:
          "A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
        popularity: 1087.816,
        poster_path: "/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg",
        release_date: "2020-11-13",
        title: "Fatman",
        video: false,
        vote_average: 5.9,
        vote_count: 173,
      },
      {
        adult: false,
        backdrop_path: "/zMcEalkxEiRjvmijliLBk0sYern.jpg",
        genre_ids: [35, 80, 53],
        id: 765123,
        original_language: "de",
        original_title: "Wir Können Nicht Anders",
        overview:
          "A man foils an attempted murder, then flees the crew of would-be killers along with their intended target as a woman he's just met tries to find him.",
        popularity: 1708.274,
        poster_path: "/ajKpYK7XdzIYjy9Uy8nkgRboKyv.jpg",
        release_date: "2020-12-04",
        title: "Christmas Crossfire",
        video: false,
        vote_average: 5.2,
        vote_count: 21,
      },
      {
        adult: false,
        backdrop_path: "/tYkMtYPNpUdLdzGDUTC5atyMh9X.jpg",
        genre_ids: [28, 53, 80, 18],
        id: 553604,
        original_language: "en",
        original_title: "Honest Thief",
        overview:
          "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
        popularity: 889.616,
        poster_path: "/zeD4PabP6099gpE0STWJrJrCBCs.jpg",
        release_date: "2020-09-03",
        title: "Honest Thief",
        video: false,
        vote_average: 7.2,
        vote_count: 197,
      },
      {
        adult: false,
        backdrop_path: "/wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
        genre_ids: [28, 53, 878],
        id: 577922,
        original_language: "en",
        original_title: "Tenet",
        overview:
          "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
        popularity: 877.927,
        poster_path: "/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
        release_date: "2020-08-22",
        title: "Tenet",
        video: false,
        vote_average: 7.4,
        vote_count: 3006,
      },
      {
        adult: false,
        backdrop_path: "/fTDzKoQIh1HeyjfpG5AHMi2jxAJ.jpg",
        genre_ids: [28, 35],
        id: 682377,
        original_language: "en",
        original_title: "Chick Fight",
        overview:
          "When Anna Wyncomb is introduced to an an underground, all-female fight club in order to turn the mess of her life around, she discovers she is much more personally connected to the history of the club than she could ever imagine.",
        popularity: 832.208,
        poster_path: "/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg",
        release_date: "2020-11-13",
        title: "Chick Fight",
        video: false,
        vote_average: 5.8,
        vote_count: 65,
      },
      {
        adult: false,
        backdrop_path: "/zKv7KF0pH9ASv2uGgTvTylMlxQn.jpg",
        genre_ids: [37],
        id: 729648,
        original_language: "en",
        original_title: "The Dalton Gang",
        overview:
          "When their brother Frank is killed by an outlaw, brothers Bob Dalton, Emmett Dalton and Gray Dalton join their local sheriff's department. When they are cheated by the law, they turn to crime, robbing trains and anything else they can steal from over the course of two years in the early 1890's. Trying to out do Jesse James, they attempt to rob two banks at once in October of 1892, and things get ugly",
        popularity: 859.123,
        poster_path: "/6OeGqp18oZucUGziMIRNhLouZ75.jpg",
        release_date: "2020-11-02",
        title: "The Dalton Gang",
        video: false,
        vote_average: 4.5,
        vote_count: 42,
      },
      {
        adult: false,
        backdrop_path: "/2ltadt0HtHS8qD3xREVds3PDxkP.jpg",
        genre_ids: [10751, 14, 35],
        id: 662546,
        original_language: "en",
        original_title: "Godmothered",
        overview:
          'A young and unskilled fairy godmother that ventures out on her own to prove her worth by tracking down a young girl whose request for help was ignored. What she discovers is that the girl has now become a grown woman in need of something very different than a "prince charming."',
        popularity: 749.198,
        poster_path: "/ir8Qqi90mENhH7CDxEpdeCcm6UL.jpg",
        release_date: "2020-12-04",
        title: "Godmothered",
        video: false,
        vote_average: 7.2,
        vote_count: 184,
      },
      {
        adult: false,
        backdrop_path: "/qtq1mai9POAX2IRGcxhVpf8f6Aj.jpg",
        genre_ids: [27],
        id: 756278,
        original_language: "en",
        original_title: "Haunting of the Mary Celeste",
        overview:
          'Rachel, a concerned researcher, and her team have set out to sea to prove that the disappearance of a family and crew from a merchant ship was for reasons having to do with the supernatural. Her theory that those on the Mary Celeste vanished into a "rift" between dimensions proves true as the boat breaks down and her crew begins to vanish one by one.',
        popularity: 489.28,
        poster_path: "/csTraKglBdSeU9bLMaw9e20hEIN.jpg",
        release_date: "2020-10-23",
        title: "Haunting of the Mary Celeste",
        video: false,
        vote_average: 7.1,
        vote_count: 8,
      },
      {
        adult: false,
        backdrop_path: "/86L8wqGMDbwURPni2t7FQ0nDjsH.jpg",
        genre_ids: [28, 53],
        id: 724989,
        original_language: "en",
        original_title: "Hard Kill",
        overview:
          "The work of billionaire tech CEO Donovan Chalmers is so valuable that he hires mercenaries to protect it, and a terrorist group kidnaps his daughter just to get it.",
        popularity: 689.026,
        poster_path: "/ugZW8ocsrfgI95pnQ7wrmKDxIe.jpg",
        release_date: "2020-10-23",
        title: "Hard Kill",
        video: false,
        vote_average: 4.9,
        vote_count: 245,
      },
      {
        adult: false,
        backdrop_path: "/m7QpUAeI2xTCJyAVl9J9z5dBTSb.jpg",
        genre_ids: [878, 27, 28],
        id: 722603,
        original_language: "en",
        original_title: "Battlefield 2025",
        overview:
          "Weekend campers, an escaped convict, young lovers and a police officer experience a night of terror when a hostile visitor from another world descends on a small Arizona town.",
        popularity: 475.57,
        poster_path: "/w6e0XZreiyW4mGlLRHEG8ipff7b.jpg",
        release_date: "2020-07-07",
        title: "Battlefield 2025",
        video: false,
        vote_average: 5.6,
        vote_count: 92,
      },
      {
        adult: false,
        backdrop_path: "/eo6pahstCYRUm0Lk4MORmfCs2SH.jpg",
        genre_ids: [16],
        id: 752455,
        original_language: "en",
        original_title: "Angela's Christmas Wish",
        overview:
          "A determined Angela makes a wish to reunite her family in time for Christmas, then launches a plan to find her way from Ireland to Australia.",
        popularity: 447.816,
        poster_path: "/eu747ko823mktL3ygo7ohdZznP7.jpg",
        release_date: "2020-12-01",
        title: "Angela's Christmas Wish",
        video: false,
        vote_average: 6.3,
        vote_count: 35,
      },
      {
        adult: false,
        backdrop_path: "/gnf4Cb2rms69QbCnGFJyqwBWsxv.jpg",
        genre_ids: [53, 28, 18, 80],
        id: 671039,
        original_language: "fr",
        original_title: "Bronx",
        overview:
          "Caught in the crosshairs of police corruption and Marseille’s warring gangs, a loyal cop must protect his squad by taking matters into his own hands.",
        popularity: 623.602,
        poster_path: "/9HT9982bzgN5on1sLRmc1GMn6ZC.jpg",
        release_date: "2020-10-30",
        title: "Rogue City",
        video: false,
        vote_average: 5.9,
        vote_count: 292,
      },
      {
        adult: false,
        backdrop_path: "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
        genre_ids: [28, 53],
        id: 524047,
        original_language: "en",
        original_title: "Greenland",
        overview:
          "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
        popularity: 624.911,
        poster_path: "/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg",
        release_date: "2020-07-29",
        title: "Greenland",
        video: false,
        vote_average: 7.2,
        vote_count: 971,
      },
      {
        adult: false,
        backdrop_path: "/d2UxKyaJ5GgzuHaSsWinFfv3g6L.jpg",
        genre_ids: [28, 27, 53],
        id: 581392,
        original_language: "ko",
        original_title: "반도",
        overview:
          "A soldier and his team battle hordes of post-apocalyptic zombies in the wastelands of the Korean Peninsula.",
        popularity: 687.091,
        poster_path: "/sy6DvAu72kjoseZEjocnm2ZZ09i.jpg",
        release_date: "2020-07-15",
        title: "Peninsula",
        video: false,
        vote_average: 6.9,
        vote_count: 905,
      },
      {
        adult: false,
        backdrop_path: "/aO5ILS7qnqtFIprbJ40zla0jhpu.jpg",
        genre_ids: [28, 53, 12, 18],
        id: 741067,
        original_language: "en",
        original_title: "Welcome to Sudden Death",
        overview:
          "Jesse Freeman is a former special forces officer and explosives expert now working a regular job as a security guard in a state-of-the-art basketball arena. Trouble erupts when a tech-savvy cadre of terrorists kidnap the team's owner and Jesse's daughter during opening night. Facing a ticking clock and impossible odds, it's up to Jesse to not only save them but also a full house of fans in this highly charged action thriller.",
        popularity: 561.1,
        poster_path: "/elZ6JCzSEvFOq4gNjNeZsnRFsvj.jpg",
        release_date: "2020-09-29",
        title: "Welcome to Sudden Death",
        video: false,
        vote_average: 6.2,
        vote_count: 192,
      },
    ],
    error: null,
    status: "succeeded",
    pageNum: 2,
  },
  friends: {
    friends: [
      {
        displayName: "Otter Algae",
        genrePreference: [
          28,
          12,
          16,
          35,
          80,
          99,
          18,
          10751,
          14,
          36,
          27,
          10402,
          9648,
          10749,
          878,
          10770,
          53,
          10752,
          37,
        ],
        photoURL: null,
        uid: "wFKYBpIoL7rKuMl90M9vFJ3Huh30",
        isAnonymous: false,
        email: "otter.algae.908@test.com",
      },
    ],
    received: [],
    sent: [],
  },
  notification: {},
};
